# Generated by Django 4.1.2 on 2022-12-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_name',
        ),
    ]
