# Generated by Django 4.1.2 on 2022-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingAPP', '0002_alter_section_section_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
